version: '3'
services:
  seelescan:
    image: seele:latest
    command: start
    ports:
      - "8545:8545"
      - "8546:8546"
      - "9090:9090"
      - "9091:9091"
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
    expose:
      - "8545"
      - "8546"
      - "9090"
      - "9091"
      - "26656"
      - "26657"
      - "1317"
    volumes:
      - /data/seele:/root/.seele
      - /etc/localtime:/etc/localtime
    restart: always